RoleName="CrowdStrikeFalcon"
ExternalID="5asHGmOBSCLWqxr"
//CSAccountNumber="292230061137"
CloudTrailS3BucketName="cs-falcon-cloudtrail-xilokzwpue"
//CSAssumingRoleName="CS-Prod-HG-CsCloudconnectaws"
CloudTrailName="logging-acct-trail"
aws_local_account = "106808901653"
aws_region = "eu-west-1"